// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNzt76k3Hg-iH7Ez8VVQqIh2610h7nG0s',
    appId: '1:140979977770:web:cd8d8caa37cf14ed71cd53',
    messagingSenderId: '140979977770',
    projectId: 'notes-v2-96cd4',
    authDomain: 'notes-v2-96cd4.firebaseapp.com',
    storageBucket: 'notes-v2-96cd4.appspot.com',
    measurementId: 'G-7B0BNCSTZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX5qMNHabMSm71pfMbmbg1tVTJpXp4Gjs',
    appId: '1:140979977770:android:6bfb9bf7612c8c4a71cd53',
    messagingSenderId: '140979977770',
    projectId: 'notes-v2-96cd4',
    storageBucket: 'notes-v2-96cd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpAkicXCbNvPrCDCjcal8S_Cql4aN5H6Q',
    appId: '1:140979977770:ios:841c71bdc03cb4c971cd53',
    messagingSenderId: '140979977770',
    projectId: 'notes-v2-96cd4',
    storageBucket: 'notes-v2-96cd4.appspot.com',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpAkicXCbNvPrCDCjcal8S_Cql4aN5H6Q',
    appId: '1:140979977770:ios:841c71bdc03cb4c971cd53',
    messagingSenderId: '140979977770',
    projectId: 'notes-v2-96cd4',
    storageBucket: 'notes-v2-96cd4.appspot.com',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNzt76k3Hg-iH7Ez8VVQqIh2610h7nG0s',
    appId: '1:140979977770:web:a2c76901b2de2c9c71cd53',
    messagingSenderId: '140979977770',
    projectId: 'notes-v2-96cd4',
    authDomain: 'notes-v2-96cd4.firebaseapp.com',
    storageBucket: 'notes-v2-96cd4.appspot.com',
    measurementId: 'G-G3YMHVVQHR',
  );
}