// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6TPGqcxDU2gy9-1jYpFVKXn6v-BsCOKc',
    appId: '1:193830534442:web:826f5d070c9002ba093253',
    messagingSenderId: '193830534442',
    projectId: 'notes-ae561',
    authDomain: 'notes-ae561.firebaseapp.com',
    storageBucket: 'notes-ae561.appspot.com',
    measurementId: 'G-6LFCNJ1XP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAShimuqkeGaAYtX0MNZViq513PY7hZ4FA',
    appId: '1:193830534442:android:07611c9410eb7e6e093253',
    messagingSenderId: '193830534442',
    projectId: 'notes-ae561',
    storageBucket: 'notes-ae561.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbJXsQb95QRwKrt8ruIWiTRZG-dyPw5Hs',
    appId: '1:193830534442:ios:5156b13d65be61de093253',
    messagingSenderId: '193830534442',
    projectId: 'notes-ae561',
    storageBucket: 'notes-ae561.appspot.com',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbJXsQb95QRwKrt8ruIWiTRZG-dyPw5Hs',
    appId: '1:193830534442:ios:5156b13d65be61de093253',
    messagingSenderId: '193830534442',
    projectId: 'notes-ae561',
    storageBucket: 'notes-ae561.appspot.com',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6TPGqcxDU2gy9-1jYpFVKXn6v-BsCOKc',
    appId: '1:193830534442:web:b9df7352165f4078093253',
    messagingSenderId: '193830534442',
    projectId: 'notes-ae561',
    authDomain: 'notes-ae561.firebaseapp.com',
    storageBucket: 'notes-ae561.appspot.com',
    measurementId: 'G-H5RY6HJC2K',
  );
}
